steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - containers/mission.Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/nightwatch/mission:manual
timeout: 1200s
